trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '6.x'
      installationPath: $(Agent.ToolsDirectory)/dotnet

  - checkout: self

  - task: Docker@2
    inputs:
      command: 'buildAndPush'
      repository: 'thiagodasilvamenezes/unyleya_projeto_cicd_thiago_menezes'
      tags: 'latest'
      containerRegistry: 'DockerHub'
      Dockerfile: '**/Dockerfile'
